# https://github.com/MrCow98/MilkyGreet
# Also major thanks to dkim19375 for helping out a ton https://github.com/dkim19375

# This section will be what the plugin says when it starts and stops. (no need to touch this though)
startup-message: "Welcome to MilkyGreet!"
stop-message: "Shutting down MilkyGreet..."

# This section will change what the plugin says when a player joins, and when a player leaves
join-message: "Welcome %player%"
quit-message: "Goodbye %player%"